@id=4d650efd-a826-4e93-835e-82636fef1de4

PUT http://localhost:5235/breakfasts/{{id}}
Content-Type: application/json

{
  "Name": "WAFFLES",
  "Description": "Fluffy pancakes with maple syrup",
  "StartDateTime": "2023-10-01T08:00:00",
  "EndDateTime": "2023-10-01T10:00:00",
  "Ingredients": ["flour", "milk", "eggs", "sugar", "baking powder"]
}